/* ==========================================================
   Calculation generators (KS3: g = 10 N/kg on Earth, sound 330 m/s in air, 1500 m/s in water).
   Each returns { q, ans, unit, steps[] } with fresh numbers; answers are computed so every
   question is self-consistent. Numbers are kept friendly — no standard form.
   ========================================================== */
const GEN = {};
const GEN_FLAGS = {};
const nf = x => String(+(+x).toPrecision(4));
const pk = a => a[Math.floor(Math.random() * a.length)];
const G9 = 10;

/* ---------- 1.2 Scale drawings ---------- */
GEN.scale1 = () => { const sc = pk([2, 5, 10, 20, 50]), L = rnd(1.5, 9, 0.5), F = L * sc; return Math.random() < .5
  ? { q: `A force diagram uses the scale 1 cm = ${sc} N. How long should the arrow be for a force of ${nf(F)} N?`, ans: L, unit: 'cm', steps: [`length = force ÷ scale = ${nf(F)} ÷ ${sc}`, `= ${nf(L)} cm`] }
  : { q: `A force diagram uses the scale 1 cm = ${sc} N. An arrow is ${nf(L)} cm long. What force does it show?`, ans: F, unit: 'N', steps: [`force = length × scale = ${nf(L)} × ${sc}`, `= ${nf(F)} N`] }; };

/* ---------- Means (practicals) ---------- */
GEN.mean1 = () => { const base = rnd(2, 9, 0.1), vals = Array.from({ length: pk([3, 4, 5]) }, () => +(base + (Math.random() - .5) * 0.8).toFixed(1)), m = vals.reduce((a, b) => a + b, 0) / vals.length;
  return { q: `A student’s repeat readings are ${vals.join(' N, ')} N. Calculate the mean.`, ans: m, unit: 'N', steps: [`sum = ${vals.join(' + ')} = ${nf(vals.reduce((a, b) => a + b, 0))}`, `mean = sum ÷ ${vals.length} = ${nf(m)} N`] }; };
GEN.mean2 = () => { const base = rnd(3, 8, 0.1), vals = Array.from({ length: 4 }, () => +(base + (Math.random() - .5) * 0.6).toFixed(1)), bad = +(base * pk([1.8, 2.2, 0.4])).toFixed(1), all = shuffle([...vals, bad]), m = vals.reduce((a, b) => a + b, 0) / 4;
  return { q: `Readings: ${all.join(' s, ')} s. Leave out the anomalous result and calculate the mean.`, ans: m, unit: 's', steps: [`the anomaly is ${bad} s — it does not fit the others`, `sum of the rest = ${vals.join(' + ')} = ${nf(vals.reduce((a, b) => a + b, 0))}`, `mean = ÷ 4 = ${nf(m)} s`] }; };

/* ---------- 2.1 Resultant force ---------- */
GEN.res1 = () => { const a = rnd(10, 400, 5), b = rnd(10, 400, 5); return { q: `Two people push a car in the same direction with forces of ${a} N and ${b} N. Calculate the resultant force.`, ans: a + b, unit: 'N', steps: ['Same direction → add.', `${a} + ${b} = ${a + b} N`] }; };
GEN.res2 = () => { let a = rnd(20, 900, 10), b = rnd(10, 800, 10); if (a === b) b += 10; const r = Math.abs(a - b);
  return { q: `A box is pushed to the right with ${a} N. Friction of ${b} N acts to the left. Calculate the size of the resultant force.`, ans: r, unit: 'N', steps: ['Opposite directions → subtract.', `${Math.max(a, b)} − ${Math.min(a, b)} = ${r} N`, `It acts to the ${a > b ? 'right' : 'left'} (the direction of the bigger force).`] }; };
GEN.res3 = () => { const d = rnd(100, 3000, 50), ar = rnd(20, 1500, 10), fr = rnd(10, 800, 10), r = d - ar - fr;
  return { q: `A vehicle has a driving force of ${d} N, air resistance of ${ar} N and friction of ${fr} N. Calculate the resultant force (use a minus sign if it acts backwards).`, ans: r, unit: 'N', steps: [`backwards forces = ${ar} + ${fr} = ${ar + fr} N`, `resultant = ${d} − ${ar + fr} = ${r} N`, r > 0 ? 'Forwards: it speeds up.' : r < 0 ? 'Backwards: it slows down.' : 'Zero: steady speed.'] }; };

/* ---------- 2.2 Springs and newton meters ---------- */
GEN.nm1 = () => { const perN = pk([0.5, 1, 1.5, 2, 2.5, 3, 4]), F1 = pk([1, 2, 3, 4]), F2 = rnd(1, 8, 0.5), e1 = perN * F1, e2 = perN * F2;
  return { q: `A spring stretches ${nf(e1)} cm when a force of ${F1} N is applied. Assuming it obeys Hooke’s law, how far will it stretch with ${nf(F2)} N?`, ans: e2, unit: 'cm', steps: [`1 N stretches it ${nf(e1)} ÷ ${F1} = ${nf(perN)} cm`, `${nf(F2)} N → ${nf(F2)} × ${nf(perN)} = ${nf(e2)} cm`] }; };
GEN.nm2 = () => { const max = pk([5, 10, 20, 50]), div = pk([5, 10, 4, 2]), whole = max / 10, dv = whole / div, k = rnd(1, 9, 1), n = rnd(1, div - 1, 1), R = whole * k + dv * n;
  return { q: `A newton meter has numbered marks every ${nf(whole)} N, with ${div} small divisions between each numbered mark. The pointer is ${n} small division${n > 1 ? 's' : ''} past the ${nf(whole * k)} N mark. What is the reading?`, ans: R, unit: 'N', steps: [`one division = ${nf(whole)} ÷ ${div} = ${nf(dv)} N`, `reading = ${nf(whole * k)} + ${n} × ${nf(dv)} = ${nf(R)} N`] }; };
GEN.ext1 = () => { const L0 = rnd(4, 20, 0.5), e = rnd(0.5, 12, 0.5); return { q: `A spring is ${nf(L0)} cm long. When a weight is hung on it, it is ${nf(L0 + e)} cm long. Calculate the extension.`, ans: e, unit: 'cm', steps: ['extension = stretched length − original length', `= ${nf(L0 + e)} − ${nf(L0)} = ${nf(e)} cm`] }; };

/* ---------- 3 Weight ---------- */
GEN.wt1 = () => { const m = pk([rnd(1, 90, 1), rnd(0.1, 5, 0.1)]), W = m * G9; return { q: `Calculate the weight of a ${nf(m)} kg object on Earth. (g = 10 N/kg)`, ans: W, unit: 'N', steps: ['$W = m × g$', `$W = ${nf(m)} × 10$`, `$W = ${nf(W)} "N"$`] }; };
GEN.wt2 = () => { const grams = rnd(50, 950, 50), W = grams / 1000 * G9; return { q: `Calculate the weight of ${grams} g of flour on Earth. (g = 10 N/kg)`, ans: W, unit: 'N', steps: [`${grams} g = ${nf(grams / 1000)} kg`, `$W = ${nf(grams / 1000)} × 10$`, `$W = ${nf(W)} "N"$`] }; };
GEN.wt3 = () => { const m = rnd(2, 120, 1), W = m * G9; return { q: `An object weighs ${W} N on Earth. What is its mass? (g = 10 N/kg)`, ans: m, unit: 'kg', steps: ['$m = @frac{W}{g}$', `$m = @frac{${W}}{10}$`, `$m = ${m} "kg"$`] }; };
const PLANETS = [['the Moon', 1.6], ['Mars', 3.7], ['Mercury', 3.7], ['Venus', 8.9], ['Jupiter', 25], ['Saturn', 10.4], ['Neptune', 11]];
GEN.planet1 = () => { const [p, gp] = pk(PLANETS), m = rnd(5, 150, 5), W = m * gp; return { q: `A ${m} kg robot lands on ${p}, where g = ${gp} N/kg. Calculate its weight there.`, ans: W, unit: 'N', steps: ['$W = m × g$', `$W = ${m} × ${gp}$`, `$W = ${nf(W)} "N"$`] }; };
GEN.planet2 = () => { const [p, gp] = pk(PLANETS), m = rnd(20, 100, 5), WE = m * G9, W = m * gp; return { q: `An astronaut weighs ${WE} N on Earth (g = 10 N/kg). What does she weigh on ${p} (g = ${gp} N/kg)?`, ans: W, unit: 'N', steps: [`mass = ${WE} ÷ 10 = ${m} kg (the same everywhere)`, `$W = ${m} × ${gp}$`, `$W = ${nf(W)} "N"$`] }; };

/* ---------- 4 Density ---------- */
const MATS = [['aluminium', 2.7], ['iron', 7.9], ['copper', 8.9], ['lead', 11.3], ['glass', 2.5], ['oak', 0.7], ['ice', 0.92], ['cork', 0.24], ['gold', 19.3], ['granite', 2.7]];
GEN.den1 = () => { const [n, d] = pk(MATS), V = rnd(5, 200, 5), m = d * V; return { q: `A sample has a mass of ${nf(m)} g and a volume of ${V} cm³. Calculate its density.`, ans: d, unit: 'g/cm³', steps: ['$ρ = @frac{m}{V}$', `$ρ = @frac{${nf(m)}}{${V}}$`, `$ρ = ${d} "g/cm"^3$ (${n})`] }; };
GEN.den2 = () => { const [n, d] = pk(MATS), V = rnd(10, 500, 10), m = d * V; return { q: `${n[0].toUpperCase() + n.slice(1)} has a density of ${d} g/cm³. Calculate the mass of ${V} cm³ of it.`, ans: m, unit: 'g', steps: ['$m = ρ × V$', `$m = ${d} × ${V}$`, `$m = ${nf(m)} "g"$`] }; };
GEN.den3 = () => { const [n, d] = pk(MATS), V = rnd(5, 100, 5), m = d * V; return { q: `A piece of ${n} (density ${d} g/cm³) has a mass of ${nf(m)} g. Calculate its volume.`, ans: V, unit: 'cm³', steps: ['$V = @frac{m}{ρ}$', `$V = @frac{${nf(m)}}{${d}}$`, `$V = ${V} "cm"^3$`] }; };
GEN.den4 = () => { const [n, d] = pk(MATS.slice(0, 6)), l = rnd(2, 8, 1), w = rnd(1, 5, 1), h = rnd(1, 4, 1), V = l * w * h, m = d * V; return { q: `A block measures ${l} cm × ${w} cm × ${h} cm and has a mass of ${nf(m)} g. Calculate its density.`, ans: d, unit: 'g/cm³', steps: [`volume = ${l} × ${w} × ${h} = ${V} cm³`, `$ρ = @frac{${nf(m)}}{${V}}$`, `$ρ = ${d} "g/cm"^3$ (${n})`] }; };
GEN.den5 = () => { const [n, d] = pk(MATS.filter(x => x[1] > 1)), start = rnd(20, 60, 2), V = rnd(4, 30, 1), m = d * V; return { q: `A stone of mass ${nf(m)} g is lowered into a measuring cylinder. The water level rises from ${start} cm³ to ${start + V} cm³. Calculate the density of the stone.`, ans: d, unit: 'g/cm³', steps: [`volume = ${start + V} − ${start} = ${V} cm³`, `$ρ = @frac{${nf(m)}}{${V}}$`, `$ρ = ${d} "g/cm"^3$`] }; };
const LIQ = [['water', 1.0], ['cooking oil', 0.92], ['sea water', 1.03], ['milk', 1.03], ['honey', 1.42], ['alcohol', 0.79], ['washing-up liquid', 1.06]];
GEN.den6 = () => { const [n, d] = pk(LIQ), empty = rnd(80, 160, 1), V = pk([25, 40, 50, 80, 100]), m = d * V; return { q: `An empty measuring cylinder has a mass of ${empty} g. With ${V} cm³ of ${n} in it, the mass is ${nf(empty + m)} g. Calculate the density of the ${n}.`, ans: d, unit: 'g/cm³', steps: [`mass of liquid = ${nf(empty + m)} − ${empty} = ${nf(m)} g`, `$ρ = @frac{${nf(m)}}{${V}}$`, `$ρ = ${d} "g/cm"^3$`] }; };

/* ---------- 5 Upthrust ---------- */
GEN.up1 = () => { const Wa = rnd(2, 20, 0.2), U = +(Wa * pk([0.1, 0.15, 0.2, 0.3, 0.35, 0.4])).toFixed(1), Ww = +(Wa - U).toFixed(1); return { q: `An object weighs ${nf(Wa)} N in air and ${nf(Ww)} N when fully under water. Calculate the upthrust.`, ans: U, unit: 'N', steps: ['upthrust = weight in air − weight in water', `= ${nf(Wa)} − ${nf(Ww)} = ${nf(U)} N`] }; };
GEN.up2 = () => { const V = rnd(20, 900, 10), U = V / 1000 * G9; return { q: `A stone displaces ${V} cm³ of water when fully submerged. 1 cm³ of water has a mass of 1 g. Calculate the upthrust on the stone. (g = 10 N/kg)`, ans: U, unit: 'N', steps: [`mass of water = ${V} g = ${nf(V / 1000)} kg`, `weight of water = ${nf(V / 1000)} × 10 = ${nf(U)} N`, 'upthrust = weight of water displaced'] }; };
GEN.up3 = () => { const W = rnd(5, 5000, 5), m = W / G9; return { q: `A floating boat weighs ${W} N. What mass of water does it displace? (g = 10 N/kg)`, ans: m, unit: 'kg', steps: ['floating: upthrust = weight = weight of water displaced', `mass = ${W} ÷ 10 = ${nf(m)} kg`] }; };
GEN.avgden1 = () => { const V = rnd(100, 1000, 50), d = pk([0.3, 0.5, 0.8, 0.9, 1.2, 1.5, 2]), m = d * V; return { q: `A hollow container has a total mass of ${nf(m)} g and a total volume of ${V} cm³. Calculate its average density. Will it float in water?`, ans: d, unit: 'g/cm³', steps: ['average density = total mass ÷ total volume', `= ${nf(m)} ÷ ${V} = ${d} g/cm³`, d < 1 ? 'Less than 1.0 g/cm³ → it floats.' : 'More than 1.0 g/cm³ → it sinks.'] }; };

/* ---------- 6 Energy ---------- */
GEN.kj1 = () => { const kj = rnd(0.2, 950, 0.1); return Math.random() < .5 ? { q: `Convert ${nf(kj)} kJ into joules.`, ans: kj * 1000, unit: 'J', steps: ['1 kJ = 1000 J', `${nf(kj)} × 1000 = ${nf(kj * 1000)} J`] } : { q: `Convert ${nf(kj * 1000)} J into kilojoules.`, ans: kj, unit: 'kJ', steps: ['1 kJ = 1000 J', `${nf(kj * 1000)} ÷ 1000 = ${nf(kj)} kJ`] }; };
GEN.waste1 = () => { const E = rnd(50, 5000, 50), u = Math.round(E * pk([0.1, 0.2, 0.25, 0.4, 0.6, 0.75, 0.9])); return { q: `A device is supplied with ${E} J of energy and transfers ${u} J usefully. How much energy is wasted?`, ans: E - u, unit: 'J', steps: ['wasted = total in − useful', `${E} − ${u} = ${E - u} J`] }; };
GEN.eff1 = () => { const E = rnd(100, 5000, 100), eff = pk([10, 20, 25, 30, 40, 50, 60, 75, 80, 90]), u = E * eff / 100; return { q: `★ A motor is given ${E} J and transfers ${nf(u)} J usefully. Calculate its efficiency as a percentage.`, ans: eff, unit: '%', steps: ['$"efficiency" = @frac{"useful out"}{"total in"} × 100"%"$', `= ${nf(u)} ÷ ${E} × 100`, `= ${eff}%`] }; };
GEN.gpe1 = () => { const m = rnd(1, 800, 1), h = rnd(1, 60, 1), E = m * G9 * h; return { q: `★ Calculate the gravitational potential energy gained when a ${m} kg object is lifted ${h} m. (g = 10 N/kg)`, ans: E, unit: 'J', steps: ['$"GPE" = m × g × h$', `$= ${m} × 10 × ${h}$`, `$= ${nf(E)} "J"$`] }; };
GEN.coast1 = () => { const m = rnd(200, 800, 50), h = rnd(20, 60, 5), E = m * G9 * h, w = Math.round(E * pk([0.1, 0.15, 0.2, 0.25])); return { q: `A ${m} kg coaster car at the top of a ${h} m hill has ${nf(E)} J of gravitational potential energy. By the bottom, ${nf(w)} J has been wasted by friction and air resistance. How much kinetic energy does it have at the bottom?`, ans: E - w, unit: 'J', steps: ['kinetic energy at the bottom = GPE at the top − energy wasted', `= ${nf(E)} − ${nf(w)} = ${nf(E - w)} J`] }; };

/* ---------- 8.1 Moments ---------- */
GEN.mom1 = () => { const F = rnd(5, 600, 5), d = rnd(0.1, 3, 0.05); return { q: `A force of ${F} N acts ${nf(d)} m from a pivot. Calculate the moment.`, ans: F * d, unit: 'Nm', steps: ['$M = F × d$', `$M = ${F} × ${nf(d)}$`, `$M = ${nf(F * d)} "Nm"$`] }; };
GEN.mom2 = () => { const W1 = rnd(200, 700, 10), d1 = rnd(0.5, 2.5, 0.1), d2 = rnd(0.5, 3, 0.1), W2 = W1 * d1 / d2; return { q: `A seesaw is balanced. A child weighing ${W1} N sits ${nf(d1)} m to the left of the pivot. Another child sits ${nf(d2)} m to the right. What is the second child’s weight?`, ans: W2, unit: 'N', steps: [`anticlockwise moment = ${W1} × ${nf(d1)} = ${nf(W1 * d1)} Nm`, 'balanced: clockwise moment = anticlockwise moment', `weight = ${nf(W1 * d1)} ÷ ${nf(d2)} = ${nf(W2)} N`] }; };
GEN.mom3 = () => { const W1 = rnd(1, 10, 1), d1 = rnd(10, 45, 5), W2 = rnd(1, 10, 1), d2 = W1 * d1 / W2; if (d2 > 50 || d2 < 2) return GEN.mom3(); return { q: `A metre rule balances at its centre. A ${W1} N weight hangs ${d1} cm to the left of the centre. How far to the right must a ${W2} N weight hang to balance it?`, ans: d2, unit: 'cm', steps: [`anticlockwise moment = ${W1} × ${d1} = ${W1 * d1} N cm`, `distance = ${W1 * d1} ÷ ${W2}`, `= ${nf(d2)} cm`] }; };

/* ---------- 8.3 Speed ---------- */
GEN.spd1 = () => { const v = pk([rnd(1, 12, 0.5), rnd(10, 40, 1)]), t = rnd(4, 120, 1), d = v * t; return { q: `A runner covers ${nf(d)} m in ${t} s. Calculate her average speed.`, ans: v, unit: 'm/s', steps: ['$v = @frac{d}{t}$', `$v = @frac{${nf(d)}}{${t}}$`, `$v = ${nf(v)} "m/s"$`] }; };
GEN.spd2 = () => { const v = rnd(2, 30, 1), mins = rnd(1, 20, 1), d = v * mins * 60; return { q: `A car travels at ${v} m/s for ${mins} minute${mins > 1 ? 's' : ''}. How far does it travel?`, ans: d, unit: 'm', steps: [`t = ${mins} × 60 = ${mins * 60} s`, '$d = v × t$', `$d = ${v} × ${mins * 60} = ${nf(d)} "m"$`] }; };
GEN.spd3 = () => { const v = pk([1.5, 2, 4, 5, 6, 8, 10, 12, 15, 20, 25]), t = rnd(10, 400, 10), d = v * t; return { q: `How long does it take to travel ${nf(d)} m at ${v} m/s?`, ans: t, unit: 's', steps: ['$t = @frac{d}{v}$', `$t = @frac{${nf(d)}}{${v}}$`, `$t = ${t} "s"$`] }; };
GEN.spd4 = () => { const km = rnd(1, 30, 0.5), min = rnd(5, 90, 5), v = km * 1000 / (min * 60); return { q: `A cyclist rides ${nf(km)} km in ${min} minutes. Calculate her average speed in m/s.`, ans: v, unit: 'm/s', steps: [`d = ${nf(km)} km = ${nf(km * 1000)} m; t = ${min} × 60 = ${min * 60} s`, `$v = @frac{${nf(km * 1000)}}{${min * 60}}$`, `$v = ${nf(v)} "m/s"$`] }; };

/* ---------- 8.4 Distance–time graphs ---------- */
GEN.dtg1 = () => { const t1 = rnd(0, 40, 5), dt = rnd(10, 60, 5), v = rnd(1, 12, 0.5), d1 = rnd(0, 200, 10), d2 = d1 + v * dt; return { q: `A straight section of a distance–time graph goes from (${t1} s, ${d1} m) to (${t1 + dt} s, ${nf(d2)} m). Calculate the speed.`, ans: v, unit: 'm/s', steps: [`change in distance = ${nf(d2)} − ${d1} = ${nf(d2 - d1)} m`, `change in time = ${t1 + dt} − ${t1} = ${dt} s`, `speed = ${nf(d2 - d1)} ÷ ${dt} = ${nf(v)} m/s`] }; };
GEN.dtg2 = () => { const a = rnd(100, 800, 50), ta = rnd(40, 200, 10), rest = rnd(20, 120, 10), b = rnd(100, 900, 50), tb = rnd(40, 200, 10), v = (a + b) / (ta + rest + tb); return { q: `On a journey someone travels ${a} m in ${ta} s, stops for ${rest} s, then travels ${b} m in ${tb} s. Calculate the average speed for the whole journey.`, ans: v, unit: 'm/s', steps: [`total distance = ${a} + ${b} = ${a + b} m`, `total time = ${ta} + ${rest} + ${tb} = ${ta + rest + tb} s`, `average speed = ${a + b} ÷ ${ta + rest + tb} = ${nf(v)} m/s`] }; };

/* ---------- 8.5–8.7 Pressure ---------- */
GEN.pr1 = () => { const F = rnd(10, 5000, 10), A = pk([0.01, 0.02, 0.05, 0.1, 0.2, 0.25, 0.5, 1, 2, 4]), p = F / A; return { q: `A force of ${F} N acts on an area of ${A} m². Calculate the pressure.`, ans: p, unit: 'Pa', steps: ['$p = @frac{F}{A}$', `$p = @frac{${F}}{${A}}$`, `$p = ${nf(p)} "Pa"$ (N/m²)`] }; };
GEN.pr2 = () => { const F = rnd(20, 900, 10), A = rnd(2, 400, 2), p = F / A; return { q: `A box weighing ${F} N rests on a face of area ${A} cm². Calculate the pressure in N/cm².`, ans: p, unit: 'N/cm²', steps: ['$p = @frac{F}{A}$', `$p = @frac{${F}}{${A}}$`, `$p = ${nf(p)} "N/cm"^2$`] }; };
GEN.pr3 = () => { const p = rnd(100, 20000, 100), A = pk([0.01, 0.05, 0.1, 0.2, 0.5, 1.5, 2]), F = p * A; return { q: `The pressure under a block is ${p} Pa and its base area is ${A} m². Calculate the force it exerts.`, ans: F, unit: 'N', steps: ['$F = p × A$', `$F = ${p} × ${A}$`, `$F = ${nf(F)} "N"$`] }; };
GEN.pr4 = () => { const m = rnd(30, 80, 1), sq = rnd(120, 260, 1), feet = pk([1, 2]), W = m * G9, p = W / (sq * feet); return { q: `A student of mass ${m} kg draws round one shoe on 1 cm squared paper and counts ${sq} squares. Calculate the pressure on the floor when standing on ${feet === 2 ? 'both feet' : 'one foot'}. (g = 10 N/kg)`, ans: p, unit: 'N/cm²', steps: [`weight = ${m} × 10 = ${W} N`, `area = ${feet === 2 ? `2 × ${sq} = ${2 * sq}` : sq} cm²`, `p = ${W} ÷ ${sq * feet} = ${nf(p)} N/cm²`] }; };
GEN.pr5 = () => { const F1 = rnd(10, 200, 5), A1 = pk([1, 2, 4, 5, 10]), A2 = pk([50, 80, 100, 200, 250, 400]), p = F1 / A1, F2 = p * A2; return { q: `In a hydraulic jack, a force of ${F1} N pushes on a small piston of area ${A1} cm². The large piston has an area of ${A2} cm². Calculate the force on the large piston.`, ans: F2, unit: 'N', steps: [`pressure = ${F1} ÷ ${A1} = ${nf(p)} N/cm²`, 'the same pressure acts on the large piston', `F = ${nf(p)} × ${A2} = ${nf(F2)} N`] }; };
GEN.pr6 = () => { const [n, d] = pk([['water', 1000], ['sea water', 1030], ['oil', 900]]), h = rnd(0.5, 20, 0.5), p = h * d * G9; return { q: `★ Calculate the pressure due to ${n} (density ${d} kg/m³) at a depth of ${nf(h)} m. (g = 10 N/kg)`, ans: p, unit: 'Pa', steps: ['$p = h × ρ × g$', `$p = ${nf(h)} × ${d} × 10$`, `$p = ${nf(p)} "Pa"$`] }; };
GEN.pr7 = () => { const A = rnd(10, 500, 10), F = 10 * A; return { q: `Atmospheric pressure is about 10 N/cm². Calculate the force of the air on a surface of area ${A} cm².`, ans: F, unit: 'N', steps: ['$F = p × A$', `$F = 10 × ${A}$`, `$F = ${F} "N"$`] }; };

/* ---------- 9 Electricity ---------- */
GEN.ma1 = () => { const mA = rnd(5, 2500, 5); return Math.random() < .5 ? { q: `Convert ${mA} mA into amps.`, ans: mA / 1000, unit: 'A', steps: ['1 A = 1000 mA', `${mA} ÷ 1000 = ${nf(mA / 1000)} A`] } : { q: `Convert ${nf(mA / 1000)} A into milliamps.`, ans: mA, unit: 'mA', steps: ['1 A = 1000 mA', `${nf(mA / 1000)} × 1000 = ${mA} mA`] }; };
GEN.ser1 = () => { const V = pk([3, 4.5, 6, 9, 12]), v1 = +(V * pk([0.2, 0.25, 0.4, 0.5, 0.6, 0.75])).toFixed(2); return { q: `Two lamps are in series with a ${V} V battery. The p.d. across the first lamp is ${nf(v1)} V. What is the p.d. across the second lamp?`, ans: V - v1, unit: 'V', steps: ['In series the supply p.d. is shared.', `${V} − ${nf(v1)} = ${nf(V - v1)} V`] }; };
GEN.par1 = () => { const i1 = rnd(0.1, 1.5, 0.05), i2 = rnd(0.1, 1.5, 0.05); return Math.random() < .5 ? { q: `Two lamps are in parallel. The branch currents are ${nf(i1)} A and ${nf(i2)} A. What is the current from the cell?`, ans: i1 + i2, unit: 'A', steps: ['Parallel: branch currents add up.', `${nf(i1)} + ${nf(i2)} = ${nf(i1 + i2)} A`] } : { q: `In a parallel circuit the current from the cell is ${nf(i1 + i2)} A. One branch carries ${nf(i1)} A. What does the other branch carry?`, ans: i2, unit: 'A', steps: ['Parallel: branch currents add up to the total.', `${nf(i1 + i2)} − ${nf(i1)} = ${nf(i2)} A`] }; };
GEN.ohm1 = () => { const R = pk([2, 4, 5, 6, 8, 10, 12, 15, 20, 24, 30, 40, 50, 100]), I = pk([0.05, 0.1, 0.2, 0.25, 0.3, 0.4, 0.5, 0.6, 0.8, 1, 1.2, 1.5, 2]), V = R * I; return { q: `The p.d. across a resistor is ${nf(V)} V and the current through it is ${I} A. Calculate its resistance.`, ans: R, unit: 'Ω', steps: ['$R = @frac{V}{I}$', `$R = @frac{${nf(V)}}{${I}}$`, `$R = ${R} "Ω"$`] }; };
GEN.ohm2 = () => { const R = pk([2, 5, 10, 12, 20, 25, 40, 47, 100]), I = pk([0.1, 0.2, 0.25, 0.3, 0.5, 0.75, 1.2, 2]), V = R * I; return { q: `A current of ${I} A flows through a ${R} Ω resistor. Calculate the p.d. across it.`, ans: V, unit: 'V', steps: ['$V = I × R$', `$V = ${I} × ${R}$`, `$V = ${nf(V)} "V"$`] }; };
GEN.ohm3 = () => { const V = pk([1.5, 3, 4.5, 6, 9, 12, 24, 230]), R = pk([3, 5, 6, 10, 15, 20, 30, 60, 100]), I = V / R; return { q: `A ${R} Ω lamp is connected to a ${V} V supply. Calculate the current.`, ans: I, unit: 'A', steps: ['$I = @frac{V}{R}$', `$I = @frac{${V}}{${R}}$`, `$I = ${nf(I)} "A"$`] }; };
GEN.wire1 = () => { const L1 = pk([10, 20, 25, 40, 50]), R1 = rnd(0.5, 6, 0.5), L2 = pk([30, 60, 75, 80, 100, 120, 150]), R2 = R1 * L2 / L1; return { q: `${L1} cm of a wire has a resistance of ${nf(R1)} Ω. Resistance is proportional to length. What is the resistance of ${L2} cm of the same wire?`, ans: R2, unit: 'Ω', steps: [`${L2} ÷ ${L1} = ${nf(L2 / L1)} times as long`, `R = ${nf(R1)} × ${nf(L2 / L1)} = ${nf(R2)} Ω`] }; };

/* ---------- 10 Sound ---------- */
GEN.snd1 = () => { const t = rnd(1, 15, 0.5), d = 330 * t; return { q: `You count ${nf(t)} s between a lightning flash and the thunder. How far away was the lightning? (speed of sound = 330 m/s)`, ans: d, unit: 'm', steps: ['$d = v × t$', `$d = 330 × ${nf(t)}$`, `$d = ${nf(d)} "m"$`] }; };
GEN.snd2 = () => { const v = rnd(310, 350, 5), t = rnd(0.5, 3, 0.1), d = v * t; return { q: `Timers ${nf(d)} m away from a starting pistol measure ${nf(t)} s between seeing the smoke and hearing the bang. Calculate the speed of sound.`, ans: v, unit: 'm/s', steps: ['$v = @frac{d}{t}$', `$v = @frac{${nf(d)}}{${nf(t)}}$`, `$v = ${nf(v)} "m/s"$`] }; };
GEN.db1 = () => { const d0 = pk([0.5, 1, 2]), L0 = rnd(70, 90, 1), k = pk([1, 2, 3]), d = d0 * 2 ** k, L = L0 - 6 * k; return { q: `A buzzer measures ${L0} dB at ${d0} m. The loudness falls by 6 dB each time the distance doubles. Predict the reading at ${d} m.`, ans: L, unit: 'dB', steps: [`${d0} m → ${d} m is ${k} doubling${k > 1 ? 's' : ''}`, `${L0} − ${k} × 6 = ${L} dB`] }; };
GEN.echo1 = () => { const [m, v] = pk([['air', 330], ['water', 1500]]), t = m === 'air' ? rnd(0.2, 3, 0.1) : rnd(0.1, 4, 0.1), d = v * t / 2; return { q: `An echo returns ${nf(t)} s after a sound pulse is sent through ${m} (speed ${v} m/s). How far away is the reflecting surface?`, ans: d, unit: 'm', steps: [`distance there and back = ${v} × ${nf(t)} = ${nf(v * t)} m`, `distance to the surface = ÷ 2 = ${nf(d)} m`] }; };
GEN.echo2 = () => { const D = rnd(40, 120, 5), n = pk([10, 20]), v = rnd(320, 345, 5), T = n * 2 * D / v; return { q: `A student stands ${D} m from a wall and claps in time with the echoes. She times ${n} clap–echo intervals in ${nf(T)} s. Calculate the speed of sound.`, ans: n * 2 * D / +nf(T), unit: 'm/s', steps: [`each interval: sound travels 2 × ${D} = ${2 * D} m`, `total distance = ${n} × ${2 * D} = ${n * 2 * D} m`, `speed = ${n * 2 * D} ÷ ${nf(T)} = ${nf(n * 2 * D / +nf(T))} m/s`] }; };

/* ---------- 11 Light ---------- */
GEN.light1 = () => { const [what, d] = pk([['the Sun to the Earth', 150000000], ['the Moon to the Earth', 384000], ['Mars to the Earth (when close)', 78000000]]), t = d / 300000; return { q: `★ Light travels at 300 000 km/s. How long does light take to travel from ${what}, a distance of ${d.toLocaleString('en-GB')} km?`, ans: t, unit: 's', steps: ['$t = @frac{d}{v}$', `$t = ${d} ÷ 300 000$`, `$t = ${nf(t)} "s"$`] }; };
GEN.pin1 = () => { const h = rnd(0.5, 20, 0.5), D = rnd(2, 60, 1), di = pk([0.1, 0.15, 0.2, 0.25, 0.3]), hi = h * di / D * 100; return { q: `★ A pinhole camera is ${di * 100} cm long. It is pointed at an object ${nf(h)} m tall, ${D} m away. Calculate the height of the image in cm.`, ans: hi, unit: 'cm', steps: ['image height = object height × image distance ÷ object distance', `= ${nf(h)} × ${di} ÷ ${D} = ${nf(hi / 100)} m`, `= ${nf(hi)} cm`] }; };

/* ---------- Skills ---------- */
GEN.conv1 = () => { const c = pk([['km', 'm', 1000], ['m', 'cm', 100], ['cm', 'mm', 10], ['kg', 'g', 1000], ['minutes', 's', 60], ['hours', 's', 3600], ['A', 'mA', 1000]]), x = rnd(0.5, 12, 0.5); return { q: `Convert ${nf(x)} ${c[0]} into ${c[1]}.`, ans: x * c[2], unit: c[1], steps: [`1 ${c[0].replace(/s$/, '')} = ${c[2]} ${c[1]}`, `${nf(x)} × ${c[2]} = ${nf(x * c[2])} ${c[1]}`] }; };
GEN.conv2 = () => { const c = pk([['m', 'km', 1000], ['cm', 'm', 100], ['mm', 'cm', 10], ['g', 'kg', 1000], ['s', 'minutes', 60], ['mA', 'A', 1000]]), y = rnd(1, 20, 0.5), x = y * c[2]; return { q: `Convert ${nf(x)} ${c[0]} into ${c[1]}.`, ans: y, unit: c[1], steps: [`1 ${c[1].replace(/s$/, '')} = ${c[2]} ${c[0]}`, `${nf(x)} ÷ ${c[2]} = ${nf(y)} ${c[1]}`] }; };
GEN.grad1 = () => { const k = pk([0.5, 2, 2.5, 4, 5, 10, 25]), x2 = rnd(4, 40, 2), y2 = k * x2, xp = rnd(1, x2 - 1, 1); return { q: `A straight-line graph goes through the origin and the point (${x2}, ${nf(y2)}). Use it to find the y-value when x = ${xp}.`, ans: k * xp, unit: '', steps: [`gradient = ${nf(y2)} ÷ ${x2} = ${nf(k)}`, `y = ${nf(k)} × ${xp} = ${nf(k * xp)}`] }; };
