/* ==========================================================
   GCSE calculation generators (Stride · Eduqas GCSE PE).
   Training zones, fitness-test data, energy balance in kcal, and heart and lung values.
   ========================================================== */
const GTESTS = [['multi-stage fitness test level', 5, 13, 0.1, ''], ['Cooper 12-minute run', 1600, 3200, 50, 'm'], ['vertical jump', 30, 65, 1, 'cm'], ['sit and reach', 5, 35, 1, 'cm'], ['30 m sprint', 3.9, 5.4, 0.01, 's'],
  ['handgrip strength', 20, 60, 1, 'kg'], ['1-minute press-up test', 12, 55, 1, 'reps'], ['1-minute sit-up test', 15, 50, 1, 'reps'], ['stork balance', 10, 50, 1, 's'], ['Illinois agility run', 15.2, 21, 0.1, 's'], ['alternate-hand wall toss (30 s)', 15, 40, 1, 'catches']];
const lowerBetter = n => /sprint|Illinois/.test(n);
GEN.gpct = () => { const [n, lo, hi, st, u] = pk(GTESTS), a = rnd(lo, hi, st), dp = st < 0.1 ? 2 : st < 1 ? 1 : 0, b = +(a * (1 + (lowerBetter(n) ? -rnd(2, 8, 0.5) : rnd(4, 25, 1)) / 100)).toFixed(dp), pc = (b - a) / a * 100;
  return { q: `A student’s ${n} result changes from ${a}${u ? ' ' + u : ''} to ${b}${u ? ' ' + u : ''} after an 8-week training programme. Calculate the percentage change (use a negative value for a decrease).`, ans: pc, unit: '%',
    steps: ['% change = (new − old) ÷ old × 100', `= (${b} − ${a}) ÷ ${a} × 100`, `= ${r1(pc)}%`, lowerBetter(n) ? 'A lower time is an improvement here.' : 'A higher score is an improvement here.'] }; };
GEN.gmean = () => { const [n, lo, hi, st, u] = pk(GTESTS), xs = Array.from({ length: pk([3, 4, 5]) }, () => rnd(lo, hi, st)), sum = xs.reduce((a, b) => a + b, 0), m = sum / xs.length;
  return { q: `A student records ${xs.length} trials of the ${n}: ${xs.join(', ')}${u ? ' ' + u : ''}. Calculate the mean.`, ans: m, unit: u, steps: [`sum = ${r2(sum)}`, `mean = ${r2(sum)} ÷ ${xs.length} = ${r2(m)}${u ? ' ' + u : ''}`] }; };
GEN.grange = () => { const [n, lo, hi, st, u] = pk(GTESTS), xs = Array.from({ length: 5 }, () => rnd(lo, hi, st)), r = Math.max(...xs) - Math.min(...xs);
  return { q: `Five students’ ${n} results are ${xs.join(', ')}${u ? ' ' + u : ''}. Calculate the range.`, ans: r, unit: u, steps: ['range = highest − lowest', `= ${Math.max(...xs)} − ${Math.min(...xs)} = ${r2(r)}${u ? ' ' + u : ''}`] }; };
GEN.zone = () => { const age = rnd(14, 50, 1), mx = 220 - age, z = pk([['aerobic', 60, 80], ['anaerobic', 80, 90]]), which = pk(['lo', 'hi']), pc = which === 'lo' ? z[1] : z[2], v = mx * pc / 100;
  return { q: `A ${age}-year-old wants to train in the ${z[0]} training zone (${z[1]}–${z[2]}% of maximum heart rate). Calculate the ${which === 'lo' ? 'lower' : 'upper'} limit of the zone in bpm.`, ans: v, unit: 'bpm', steps: [`maximum HR = 220 − ${age} = ${mx} bpm`, `${pc}% of ${mx} = ${pc / 100} × ${mx} = ${r1(v)} bpm`] }; };
GEN.zonepc = () => { const age = rnd(14, 45, 1), mx = 220 - age, hr = rnd(Math.round(mx * 0.5), Math.round(mx * 0.95), 1), pc = hr / mx * 100;
  return { q: `A ${age}-year-old’s heart rate during a run is ${hr} bpm. What percentage of maximum heart rate is this? Which training zone is it in?`, ans: pc, unit: '%', steps: [`maximum HR = 220 − ${age} = ${mx} bpm`, `% = ${hr} ÷ ${mx} × 100 = ${r1(pc)}%`, pc < 60 ? 'Below 60% — below the aerobic training zone.' : pc <= 80 ? '60–80% — the aerobic training zone.' : pc <= 90 ? '80–90% — the anaerobic training zone.' : 'Above 90% — close to maximum.'] }; };
GEN.kcal = () => { const inn = rnd(1800, 3400, 50), bmr = rnd(1300, 1800, 10), act = rnd(250, 1300, 10), out = bmr + act, d = inn - out;
  return { q: `A student eats ${inn} kcal in a day. Their body uses ${bmr} kcal at rest and ${act} kcal in physical activity. Calculate the energy balance (use a negative value for a deficit).`, ans: d, unit: 'kcal', steps: ['energy balance = energy in − energy out', `energy out = ${bmr} + ${act} = ${out} kcal`, `${inn} − ${out} = ${d} kcal`, d > 0 ? 'Positive energy balance → weight gain over time.' : d < 0 ? 'Negative energy balance → weight loss over time.' : 'Balanced → weight stays the same.'] }; };
GEN.kcalact = () => { const rate = pk([[ 'swimming', 9 ], ['running', 11], ['cycling', 8], ['football', 9], ['walking', 4.5], ['netball', 7]]), mins = rnd(20, 90, 5), k = rate[1] * mins;
  return { q: `${rate[0][0].toUpperCase() + rate[0].slice(1)} uses about ${rate[1]} kcal per minute. How many kcal are used in ${mins} minutes?`, ans: k, unit: 'kcal', steps: [`${rate[1]} × ${mins} = ${r1(k)} kcal`] }; };
GEN.gcardout = () => { const rest = pk([true, false]), hr = rest ? rnd(50, 80, 1) : rnd(120, 195, 1), sv = rest ? rnd(60, 100, 5) : rnd(100, 180, 5), q = hr * sv / 1000;
  return { q: `${rest ? 'At rest' : 'During exercise'}, a student’s heart rate is ${hr} bpm and stroke volume is ${sv} ml. Calculate cardiac output in L/min.`, ans: q, unit: 'L/min', steps: ['cardiac output = heart rate × stroke volume', `= ${hr} × ${sv} = ${hr * sv} ml/min`, `÷ 1000 = ${r2(q)} L/min`] }; };
GEN.gsv = () => { const hr = rnd(50, 190, 1), sv = rnd(60, 170, 5), qml = hr * sv;
  return { q: `Cardiac output is ${r2(qml / 1000)} L/min and heart rate is ${hr} bpm. Calculate stroke volume in ml.`, ans: qml / hr, unit: 'ml', steps: ['stroke volume = cardiac output ÷ heart rate', `${r2(qml / 1000)} L/min = ${qml} ml/min`, `${qml} ÷ ${hr} = ${r1(qml / hr)} ml`] }; };
GEN.gve = () => { const ex = pk([true, false]), tv = ex ? rnd(1.5, 3, 0.1) : rnd(0.4, 0.6, 0.05), f = ex ? rnd(25, 50, 1) : rnd(12, 16, 1), ve = tv * f;
  return { q: `${ex ? 'During exercise' : 'At rest'}, tidal volume is ${tv} L and breathing frequency is ${f} breaths per minute. Calculate minute ventilation.`, ans: ve, unit: 'L/min', steps: ['minute ventilation = tidal volume × breathing frequency', `= ${tv} × ${f} = ${r1(ve)} L/min`] }; };
GEN.grecov = () => { const peak = rnd(150, 190, 1), rest = rnd(55, 75, 1), after = rnd(rest + 10, peak - 30, 1), drop = peak - after;
  return { q: `A student’s heart rate is ${peak} bpm at the end of a run and ${after} bpm one minute later. Resting heart rate is ${rest} bpm. By how many bpm has heart rate fallen in the first minute of recovery?`, ans: drop, unit: 'bpm', steps: [`${peak} − ${after} = ${drop} bpm`, 'A faster fall in recovery heart rate is a sign of better cardiovascular fitness.'] }; };
GEN.glever = () => { const ord = pk([2, 3]), ea = ord === 2 ? rnd(10, 20, 1) : rnd(2, 6, 0.5), la = ord === 2 ? rnd(3, ea - 2, 1) : rnd(25, 40, 1), ma = ea / la;
  return { q: `A ${ord === 2 ? 'second' : 'third'}-class lever has an effort arm of ${ea} cm and a load arm of ${la} cm. Calculate the mechanical advantage (effort arm ÷ load arm).`, ans: ma, unit: '', steps: ['mechanical advantage = effort arm ÷ load arm', `= ${ea} ÷ ${la} = ${r2(ma)}`, ma > 1 ? 'Greater than 1: a small effort can move a large load (second-class lever, e.g. ankle on tiptoe).' : 'Less than 1: a mechanical disadvantage, but a large range and speed of movement (third-class lever, e.g. elbow in a bicep curl).'] }; };
GEN.gpart = () => { const tot = rnd(400, 3000, 20), p = rnd(0.15, 0.7, 0.01), n = Math.round(tot * p), pc = n / tot * 100, who = pk(['Year 10 pupils', 'girls aged 14–16', 'adults in a town survey', 'disabled adults in a county survey', 'members of a youth club']);
  return { q: `In a survey of ${tot} ${who}, ${n} said they take part in sport at least once a week. Calculate the percentage.`, ans: pc, unit: '%', steps: ['percentage = part ÷ total × 100', `= ${n} ÷ ${tot} × 100 = ${r1(pc)}%`] }; };
GEN.ghydr = () => { const m = rnd(45, 90, 0.5), loss = rnd(0.3, 2.2, 0.1), pc = loss / m * 100;
  return { q: `A ${m} kg player weighs ${r1(m - loss)} kg after a match in hot weather. What percentage of body mass has been lost as sweat?`, ans: pc, unit: '%', steps: [`mass lost = ${m} − ${r1(m - loss)} = ${loss} kg`, `% = ${loss} ÷ ${m} × 100 = ${r2(pc)}%`, pc >= 2 ? 'About 2% or more — performance is likely to be affected; rehydrate.' : 'Under 2% — rehydrate, but performance is less likely to be affected.'] }; };
